CREATE TABLE IF NOT EXISTS SGD (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS MULTINOMIALNB (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    REAL_CATEGORY VARCHAR(100),
    PREDICTION VARCHAR(100)
) TABLESPACE mydbspace;
